### ISSUE TITLE
看代码不是用CDN的方式导入PDF.js的库

### ISSUE THREAD

**Issue by KaelInvoker** [DeMonLiu623/DeMon-JS-PDF#2]
看代码不是用CDN的方式导入PDF.js的库，倒像是把完整库下载下来放到本地，当离线包用了。

**Comment by iDeMonnnnnn** [comment]
刚开始是用cdn的方式（可以看博客），后面太慢了，就改成离线包了，忘记改文档了，谢谢指正。
