### ISSUE TITLE
不起作用

### ISSUE THREAD

**Issue by adping** [DeMonLiu623/DeMon-JS-PDF#3]
下载了你的代码，运行后界面显示空白，pdf链接在电脑上可以打开

**Comment by iDeMonnnnnn** [comment]
用这个测试一下 http://mozilla.github.io/pdf.js/web/viewer.html?file=yourpdfUrl //yourpdfUrl只能是链接
已知问题无法打开超过40M的pdf（猜测应该是android webview的限制）
